version: '3.8'

services:
  app:
    image: dnghkm/unite-app:latest
    container_name: unite-app
    ports:
      - "8088:8088"
    volumes:
      - /home/kdh/docker/unite/app/logs:/app/logs
      - /home/kdh/docker/unite/storage:/storage
    environment:
      TZ: Asia/Seoul
      JAVA_OPTS: "-Duser.timezone=Asia/Seoul"
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - redis
      - mysql
    networks:
      - proxy-network

  mysql:
    build:
      context: /home/kdh/docker/unite/mysql
      dockerfile: Dockerfile
    container_name: unite-mysql
    restart: always
    volumes:
      - /home/kdh/docker/unite/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - proxy-network

  redis:
    image: redis:latest
    container_name: unite-redis
    ports:
      - "6379:6379"
    volumes:
      - /home/kdh/docker/unite/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
