version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: unite-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/app/default.conf:/etc/nginx/conf.d/default.conf:ro  # default.conf 파일을 마운트
      - /home/ubuntu/certbot/conf:/etc/letsencrypt  # 인증서 파일 마운트
      - /home/ubuntu/certbot/www:/var/www/certbot  # Certbot 웹 인증 경로 마운트
    depends_on:
      - app
    networks:
      - unite-network

  app:
    image: dnghkm/unite-app:latest
    container_name: unite-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - ./unite/logs:/app/logs  # 로그 파일을 호스트에 저장
    environment:
      TZ: Asia/Seoul
      JAVA_OPTS: "-Duser.timezone=Asia/Seoul"
      SPRING_PROFILES_ACTIVE: prod
      REDIS_HOST: redis
    depends_on:
      - redis
    networks:
      - unite-network

  redis:
    image: redis:latest
    container_name: unite-redis
    ports:
      - "6379:6379"
    networks:
      - unite-network

  certbot:
    image: certbot/certbot
    container_name: unite-certbot
    volumes:
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done'"
    networks:
      - unite-network

networks:
  unite-network:
    driver: bridge
