version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: unite-nginx
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/app/default.conf:/etc/nginx/conf.d/default.conf:ro  # default.conf 파일을 마운트
    depends_on:
      - app
    networks:
      - unite-network

  app:
    image: dnghkm/unite-app:latest
    container_name: unite-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      TZ: Asia/Seoul
      JAVA_OPTS: "-Duser.timezone=Asia/Seoul"
      SPRING_PROFILES_ACTIVE: prod
      REDIS_HOST: redis
    depends_on:
      - redis
    networks:
      - unite-network

  redis:
    image: redis:latest
    container_name: unite-redis
    ports:
      - "6379:6379"
    networks:
      - unite-network

networks:
  unite-network:
    driver: bridge
