version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: unite-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/kdh/docker/unite/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/kdh/docker/unite/certbot/conf:/etc/letsencrypt
      - /home/kdh/docker/unite/certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - unite-network

  app:
    image: dnghkm/unite-app:latest
    container_name: unite-app
    build:
      context: /home/kdh/docker/unite/app
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - /home/kdh/docker/unite/app/logs:/app/logs
    environment:
      TZ: Asia/Seoul
      JAVA_OPTS: "-Duser.timezone=Asia/Seoul"
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - redis
      - mysql
    networks:
      - unite-network

  mysql:
    build:
      context: /home/kdh/docker/unite/mysql
      dockerfile: Dockerfile
    container_name: unite-mysql
    restart: always
    volumes:
      - /home/kdh/docker/unite/mysql/data:/var/lib/mysql
    networks:
      - unite-network

  redis:
    image: redis:latest
    container_name: unite-redis
    ports:
      - "6379:6379"
    volumes:
      - /home/kdh/docker/unite/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - unite-network

  certbot:
    image: certbot/certbot
    container_name: unite-certbot
    volumes:
      - /home/kdh/docker/unite/certbot/conf:/etc/letsencrypt
      - /home/kdh/docker/unite/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done'"
    networks:
      - unite-network

networks:
  unite-network:
    driver: bridge
